### PR TITLE
Dani and Collins pair programming on Accessibility

### PR DESCRIPTION
**Pull request by danifromecuador**
Dear reviewer, please check our repository for our portfolio accessibility.
1.- Page Titles: No issues found.
2.- Image Text Alternatives: No issues found.
3.- Text Headings: Lines changed: HTML: 
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L67
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L93
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L121
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L147
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L236
4.- Color Contrast: No issues found.
5.- Resize: No issues found.
6.- Interaction: Lines changed: HTML: 
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L239
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L241
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L243
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L245
Lines added:   CSS:
https://github.com/danifromecuador/portfolio/blob/Accessibility/styles.css#L458-L460
7.- Moving Content: Line changed: CSS: 
https://github.com/danifromecuador/portfolio/blob/Accessibility/styles.css#L80
8.- Multimedia: No issues found.
9.- The basic structure of the page: No issues found.

### CODE REVIEW

**Review by ha-manel — COMMENTED** [review]
# STATUS: INVALID 🔴 
Hi @danifromecuador 
I'm sure you put a lot of effort into this project but this PR is invalid because this is a pair programming activity but you've worked alone on it😓Your partner(s) needs to have some contribution to the project (commits) 👍  

Kindly fix the issue and submit the PR for review again 👍 
Best of luck!

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @danifromecuador, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linters passed ✔️
- Project accessibility ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly use a more descriptive title such as "Mark full-stack web developer" so that it would be more meaningful to user.
- [ ] Kindly take a second look at the navigation which I added to the screenshot below. The tab key cannot access the page because the right HTML tag is not used. It should use a tag so that it can also be used to navigate to the appropriate aspect of the page.
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kiplaacollo** [comment]
The following lines were changed:
https://github.com/danifromecuador/portfolio/blob/Accessibility/index.html#L18-L34

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @danifromecuador, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Linters passed ✔️ 
- Page accessibility ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] Nice one adding a tag to the navigation, however, you are yet to add the title page for it to be sufficiently descriptive. I think you forgot. You can find the line of code on line 12.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by nedjwab — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @danifromecuador    👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
